// Canonical error codes for the app. Keep this in sync with i18n/errors.json.
// User-facing messages are always resolved via t("errors", code).

export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_OAUTH_CANCELLED: "AUTH_OAUTH_CANCELLED",
  AUTH_OAUTH_PROVIDER_NOT_CONFIGURED: "AUTH_OAUTH_PROVIDER_NOT_CONFIGURED",
  AUTH_OAUTH_CALLBACK_INVALID: "AUTH_OAUTH_CALLBACK_INVALID",
  AUTH_OAUTH_FAILED: "AUTH_OAUTH_FAILED",
  AUTH_IDENTITY_LINK_FAILED: "AUTH_IDENTITY_LINK_FAILED",
  AUTH_IDENTITY_LINK_CONFLICT: "AUTH_IDENTITY_LINK_CONFLICT",
  AUTH_IDENTITY_LINK_NOT_CONFIGURED: "AUTH_IDENTITY_LINK_NOT_CONFIGURED",
  AUTH_IDENTITY_LINK_SESSION_CHANGED: "AUTH_IDENTITY_LINK_SESSION_CHANGED",
  AUTH_IDENTITY_UNLINK_FAILED: "AUTH_IDENTITY_UNLINK_FAILED",
  AUTH_IDENTITY_UNLINK_LAST_IDENTITY: "AUTH_IDENTITY_UNLINK_LAST_IDENTITY",
  AUTH_IDENTITY_UNLINK_NOT_CONFIGURED: "AUTH_IDENTITY_UNLINK_NOT_CONFIGURED",
  AUTH_IDENTITY_UNLINK_EMAIL_CONFLICT: "AUTH_IDENTITY_UNLINK_EMAIL_CONFLICT",
  AUTH_IDENTITY_UNLINK_SESSION_CHANGED: "AUTH_IDENTITY_UNLINK_SESSION_CHANGED",
  MICROPHONE_PERMISSION_DENIED: "MICROPHONE_PERMISSION_DENIED",
  MICROPHONE_UNAVAILABLE: "MICROPHONE_UNAVAILABLE",
  RECORDING_PREPARE_FAILED: "RECORDING_PREPARE_FAILED",
  RECORDING_INTERRUPTED: "RECORDING_INTERRUPTED",
  RECORDING_PAUSE_FAILED: "RECORDING_PAUSE_FAILED",
  RECORDING_RESUME_FAILED: "RECORDING_RESUME_FAILED",
  RECORDING_STOP_FAILED: "RECORDING_STOP_FAILED",
  LOCAL_STORAGE_LOW: "LOCAL_STORAGE_LOW",
  LOCAL_FILE_MISSING: "LOCAL_FILE_MISSING",
  FILE_UNSUPPORTED: "FILE_UNSUPPORTED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_READ_FAILED: "FILE_READ_FAILED",
  CAMERA_PERMISSION_DENIED: "CAMERA_PERMISSION_DENIED",
  MEDIA_PICKER_CANCELLED: "MEDIA_PICKER_CANCELLED",
  DOCUMENT_PICKER_CANCELLED: "DOCUMENT_PICKER_CANCELLED",
  NETWORK_OFFLINE: "NETWORK_OFFLINE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  STORAGE_ACCESS_DENIED: "STORAGE_ACCESS_DENIED",
  SYNC_CONFLICT: "SYNC_CONFLICT",
  DATABASE_WRITE_FAILED: "DATABASE_WRITE_FAILED",
  SESSION_DELETE_PARTIAL: "SESSION_DELETE_PARTIAL",
  LANGUAGE_SELECTION_INVALID: "LANGUAGE_SELECTION_INVALID",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;

export class AppError extends Error {
  readonly code: ErrorCodeKey;
  readonly cause?: unknown;
  constructor(code: ErrorCodeKey, message?: string, cause?: unknown) {
    super(message ?? code);
    this.code = code;
    this.cause = cause;
    this.name = "AppError";
  }
}

// Picker cancellation is not an error — helper to normalize.
export const isPickerCancellation = (code: ErrorCodeKey): boolean =>
  code === ErrorCode.MEDIA_PICKER_CANCELLED || code === ErrorCode.DOCUMENT_PICKER_CANCELLED;
